[package]
name = "heaps-lang"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
memoize = "0.4.2"
proc-macro2 = "1.0.86"
quote = "1.0.36"

[dev-dependencies]
trybuild = "1.0.99"
